### ISSUE TITLE
undefined reference to `_sp'

### ISSUE THREAD

**Issue by vircun** [Nuclei-Software/nuclei-sdk#3]
in portasm.s of freertos file ,there are a undefined reference to `_sp'.
where to define the "_sp" in la to _sp?
how to solve this problem?

**Comment by fanghuaqi** [comment]
Hi @vircun, the `_sp` is defined in the link script file, for example:

- For `SOC=hbird BOARD=hbird_eval`, the link script file of **DOWNLOAD=ilm** located in https://github.com/Nuclei-Software/nuclei-sdk/blob/master/SoC/hbird/Board/hbird_eval/Source/GCC/gcc_hbird_ilm.ld#L192

~~~
  .stack ORIGIN(ram) + LENGTH(ram) - __stack_size :
  {
    PROVIDE( _heap_end = . );
    . = __stack_size;
    PROVIDE( _sp = . );
  } >ram AT>ram 
~~~

If you have compile any of the applications, there is no undefined _sp issue, see https://doc.nucleisys.com/nuclei_sdk/quickstart.html for quick startup.

Thanks
Huaqi
