### ISSUE TITLE
nmsis_gcc.h disables gcc warnings

### ISSUE THREAD

**Issue by DagAgren** [Nuclei-Software/nuclei-sdk#32]
nmsis_gcc.h forcibly disables some warnings:

https://github.com/Nuclei-Software/nuclei-sdk/blob/master/NMSIS/Core/Include/nmsis_gcc.h#L46

This is very bad form for a system library. I want those warnings in my code, I do not want them silently disabled. If any headers are causing warnings, that code should be fixed, and warnings should not be silenced.

**Comment by fanghuaqi** [comment]
Will evalute on it and change it

**Comment by fanghuaqi** [comment]
Removed these #pragma GCC diagnostic
