### ISSUE TITLE
__set_exc_entry and related function use integer types instead of pointers.

### ISSUE THREAD

**Issue by DagAgren** [Nuclei-Software/nuclei-sdk#34]
`__set_exc_entry` and the other functions related to `mtvec` take and return the integer `rv_csr_t` type, although the values you would pass in are pointers. They should probably take and return `void *` types?

**Comment by fanghuaqi** [comment]
Hi @DagAgren , you can force type convert when you call this function, it might not be good to change the function argument type now.
