### ISSUE TITLE
SDK support for Logan nano GD32VF103CBT6 

### ISSUE THREAD

**Issue by bidyutper** [Nuclei-Software/nuclei-sdk#4]
Hi!
Can I use this sdk with Logan nano GD32VF103CBT6 board.

**Comment by fanghuaqi** [comment]
Of course, yes, you can easily port Logan nano to this SDK, by adding a new board in existing SoC support package.

**Comment by bidyutper** [comment]
Ok. Is there any reference tutorial or documentation to get started with this SDK.

**Comment by bidyutper** [comment]
found..thx

**Comment by fanghuaqi** [comment]
Hi @bidyutper , there is a [introduction README](https://github.com/Nuclei-Software/nuclei-sdk#nuclei-software-development-kit), there are simple guidance in this README, and for more details, please refer to https://doc.nucleisys.com/nuclei_sdk/quickstart.html
