### ISSUE TITLE
RCCV vs. adding clock pulses

### ISSUE THREAD

**Issue by gsauthof** [Nuclei-Software/nuclei-sdk#41]
The [GD32CVF103 User Manual (1.3)](http://www.gd32mcu.com/download/down/document_id/222/path_type/1) specifies the RTC clock calibration value (RCCV) as:

> RTC clock calibration value The value indicates how many clock pulses are ignored _or added_ every 2^20 RTC clock pulses.

(Section 4.4.2, page 59, emphasis mine)

After implementing a calibration procedure I don't think that the second (emphasized) part is true. That means it looks like the RCCV can only be used to ignore clock pulses.

(In which case, when having a clock that is too slow, one would need to decrement the prescaler and calibrate from a (then) too fast clock.)

My tests show that RCCV isn't interpreted as signed (two's complement) value.

And I can't find any other field that would work as a sign bit, either. I mean, e.g. in contrast to the GD32F1x0 where the RTC_HRFC register contains the CMSK (Calibration mask number) _and_ FREQI fields.

Can you clarify this point?

**Comment by fanghuaqi** [comment]
Sorry, we are not the chip designer of GD32VF103, so the RTC clock peripheral inside it, I am not familar with it.
