### ISSUE TITLE
Is a bug in CTEST?

### ISSUE THREAD

**Issue by yinqingw** [Nuclei-Software/nuclei-sdk#59]
in `test_csr.c`:
```
CTEST(core, icache)
{
    EnableICache();
    ASSERT_NOT_EQUAL(__RV_CSR_READ(CSR_MCACHE_CTL) & CSR_MCACHE_CTL_IE, 0);
    DisableICache();
    ASSERT_EQUAL(__RV_CSR_READ(CSR_MCACHE_CTL) & CSR_MCACHE_CTL_IE, 0);
}
```
should do 
```
__RWMB();
__FENCE_I();
```
before `EnableICache();`and`EnableICache();`?
Now，If my compilation option is `-02`,CPU may be abnormal。

**Comment by fanghuaqi** [comment]
Sorry, I cannot repeat it, could you provide more details for what cpu you are using, and changes you have made?

Tested on nx900fd and n900fd with `-O2`.

![image](https://github.com/Nuclei-Software/nuclei-sdk/assets/1538922/540dd02b-0b94-4a63-8672-4b0340f3b102)

**Comment by yinqingw** [comment]
It is a possible trouble，you could only run 
```
EnableICache();
DisableICache();
EnableICache();
DisableICache();
EnableICache();
DisableICache();
```
for enable and disable icache。It  may have appeared.

**Comment by yinqingw** [comment]
ok,thanks
