### ISSUE TITLE
openocd can't view register mtvt

### ISSUE THREAD

**Issue by quantrpeter** [Nuclei-Software/nuclei-sdk#6]
hi
   openocd can't view register mtvt , why?
thanks
Peter

**Comment by fanghuaqi** [comment]
Hi peter, if you are debug with gdb command line, you can view the mtvt(csr 0x307 in hex, 775 in dec) by command `info reg csr775), lines in openocd configuration files need to be added: https://github.com/Nuclei-Software/nuclei-sdk/blob/master/SoC/hbird/Board/hbird_eval/openocd_hbird.cfg#L30-L33

Thanks
Huaqi

**Comment by quantrpeter** [comment]
It works, thanks
