### ISSUE TITLE
Using Nuclei C Runtime library, malloc failed？

### ISSUE THREAD

**Issue by yinqingw** [Nuclei-Software/nuclei-sdk#61]
In my project，STDCLIB ?= libncrt_balanced；__HEAP_SIZE=2K;
But, void *ptr = malloc(100);
ptr = 0???
Why did this situation occur？
When STDCLIB ?= newlib_full, it is ok.

**Comment by fanghuaqi** [comment]
Which branch you are using, give me a sample app to test it.

**Comment by fanghuaqi** [comment]
If you are doing your customized SoC, you need to follow the linker script template based on evalsoc, and stub files for libncrt, did you check it?

Close it since not repeatable.

**Comment by yinqingw** [comment]
ok, I find miss `call __libc_init_array` in startup.S. Fixed it, it work ok. Thanks!

**Comment by fanghuaqi** [comment]
Yes, it is required for setup libncrt heap, see https://github.com/Nuclei-Software/nuclei-sdk/blob/670dfbe535b35a0411bb72902937a20a9864ca3d/SoC/evalsoc/Common/Source/Stubs/libncrt/stubs.c#L54-L58
