### ISSUE TITLE
openocd reg command

### ISSUE THREAD

**Issue by quantrpeter** [Nuclei-Software/nuclei-sdk#7]
Hi
   openocd reg command can't display all values of all registers. So i have to invoke command "reg a0", "reg a1" and so on, which is very slow. Any workaround?
thanks
Peter

**Comment by fanghuaqi** [comment]
Hi, you can run `info reg all-registers`, but it will not display the customized csrs, for customized csrs, you still need to use `info reg csrxxx`, `csrxxx` replace to the real csr number such as `csr775` for mtvt

**Comment by fanghuaqi** [comment]
You can also take a try with Nuclei Studio which has a gui debugger interface, see here https://www.nucleisys.com/download.php

**Comment by quantrpeter** [comment]
Seems not working, i am using riscv-none-embed-gdb, installed by xpm. What gdb i have to use?

![image](https://user-images.githubusercontent.com/50471577/92351200-997a0100-f10d-11ea-99cf-71094229ce94.png)

**Comment by fanghuaqi** [comment]
Sorry, my mistake, it should be `info reg all`. 

![图片](https://user-images.githubusercontent.com/1538922/92355553-0e056d80-f117-11ea-89eb-27781ce2de4c.png)

**Comment by quantrpeter** [comment]
Thanks, it works. But it is very slow. Is there any way to get all registers value by openocd please?

**Comment by fanghuaqi** [comment]
Sorry, I didn't find a way to read all registers by openocd.

**Comment by quantrpeter** [comment]
Thanks anyway
